// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: protos/service.proto

package infobotpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InfoBotService_Feedback_FullMethodName = "/protoinfobot.InfoBotService/Feedback"
)

// InfoBotServiceClient is the client API for InfoBotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// сервис информационного бота тг
type InfoBotServiceClient interface {
	// Оставить пользовательскую заявку
	Feedback(ctx context.Context, in *FeedbackRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type infoBotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInfoBotServiceClient(cc grpc.ClientConnInterface) InfoBotServiceClient {
	return &infoBotServiceClient{cc}
}

func (c *infoBotServiceClient) Feedback(ctx context.Context, in *FeedbackRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, InfoBotService_Feedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InfoBotServiceServer is the server API for InfoBotService service.
// All implementations must embed UnimplementedInfoBotServiceServer
// for forward compatibility.
//
// сервис информационного бота тг
type InfoBotServiceServer interface {
	// Оставить пользовательскую заявку
	Feedback(context.Context, *FeedbackRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedInfoBotServiceServer()
}

// UnimplementedInfoBotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInfoBotServiceServer struct{}

func (UnimplementedInfoBotServiceServer) Feedback(context.Context, *FeedbackRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Feedback not implemented")
}
func (UnimplementedInfoBotServiceServer) mustEmbedUnimplementedInfoBotServiceServer() {}
func (UnimplementedInfoBotServiceServer) testEmbeddedByValue()                        {}

// UnsafeInfoBotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InfoBotServiceServer will
// result in compilation errors.
type UnsafeInfoBotServiceServer interface {
	mustEmbedUnimplementedInfoBotServiceServer()
}

func RegisterInfoBotServiceServer(s grpc.ServiceRegistrar, srv InfoBotServiceServer) {
	// If the following call pancis, it indicates UnimplementedInfoBotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InfoBotService_ServiceDesc, srv)
}

func _InfoBotService_Feedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoBotServiceServer).Feedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InfoBotService_Feedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoBotServiceServer).Feedback(ctx, req.(*FeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InfoBotService_ServiceDesc is the grpc.ServiceDesc for InfoBotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InfoBotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protoinfobot.InfoBotService",
	HandlerType: (*InfoBotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Feedback",
			Handler:    _InfoBotService_Feedback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/service.proto",
}
